# Site settings
title: Computer Vision Ders Notları
description: >-
  Computer Vision dersi için sınav çalışma notları ve soruları.
url: "https://tozenbilek.github.io"
remote_theme: just-the-docs/just-the-docs

# Plugins required for the remote theme
plugins:
  - jekyll-remote-theme

# Enable search
search_enabled: true
