# Site settings
title: Üniversite Ders Notları
description: >-
  System Programming, Computer Vision ve Automata Theory dersleri için kişisel ders notları.
url: "https://tozenbilek.github.io"
remote_theme: just-the-docs/just-the-docs

# Plugins required for the remote theme
plugins:
  - jekyll-remote-theme

# Enable search
search_enabled: true

# Enable Mermaid diagrams
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"