# Site settings
title: Computer Vision Ders Notları
description: >-
  Computer Vision dersi için sınav çalışma notları ve soruları.
url: "https://tozenbilek.github.io"
remote_theme: just-the-docs/just-the-docs

# Plugins required for the remote theme
plugins:
  - jekyll-remote-theme

# Aux links for the header
aux_links:
  "GitHub Repo":
    - "https://github.com/tozenbilek/tozenbilek.github.io"

# Enable search
search_enabled: true
